### ISSUE TITLE
where is the licence?

### ISSUE THREAD

**Issue by BluePrintRandom** [visioncortex/vtracer#11]
was thinking about trying to add this as a dependancy for upbge, but I can't seem to find anything about if it's GPL compatible

**Comment by JohnJohnstone** [comment]
Seems it is MIT OR Apache-2.0. I found this is the Cargo.toml, for rust projects using cargo its often a good place to check if its not in readme or LICENCE file.

**Comment by tyt2y3** [comment]
Yes it is licensed per crate.

https://github.com/visioncortex/vtracer/blob/master/cmdapp/LICENSE-MIT
