### ISSUE TITLE
cmd app enforces a maximum "filter_speckle" of 16

### ISSUE THREAD

**Issue by lucadalli** [visioncortex/vtracer#13]
The cmd app does not allow `filter_speckle` values greater than 16:
`thread 'main' panicked at 'Out of Range Error: Filter speckle is invalid at 20. It must be within [1,16].'`

The web app allows much larger values (up to 126 on the web demo).
Is this by design?

**Comment by tyt2y3** [comment]
https://github.com/visioncortex/vtracer/blob/2448dbb3ba54272b1ef31774a3651f8d0021c215/webapp/app/index.js#L420
https://github.com/visioncortex/vtracer/blob/2448dbb3ba54272b1ef31774a3651f8d0021c215/cmdapp/src/config.rs#L382

Both would square the value before passing into the underlying converter. The GUI just so happens to display the squared value to you.

**Comment by tyt2y3** [comment]
I think it's a mistake. I originally thought they are not the same metric. Turns out they are the same (size, not area).
