### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by lucadalli** [visioncortex/vtracer#14]
I am facing the error above when attempting to run `vtracer-linux` v0.4.0 in a Netlify Function (AWS Lambda).

**Comment by tyt2y3** [comment]
I think the best way is for you to know the OS's libc version and recompile the program on it.

**Comment by lucadalli** [comment]
The older binaries didn't work because Ubuntu 18.04 also uses glibc 2.27
I recompiled on Amazon Linux 2 and it's working flawlessly.
Thanks for your help 🙏

**Comment by tyt2y3** [comment]
Awesome, glad I helped

**Comment by natuan62** [comment]
> The older binaries didn't work because Ubuntu 18.04 also uses glibc 2.27 I recompiled on Amazon Linux 2 and it's working flawlessly. Thanks for your help 🙏

I have same problem. How to recompiled it?
