### ISSUE TITLE
Default output from webapp doesn't match cmdapp

### ISSUE THREAD

**Issue by jsscheller** [visioncortex/vtracer#20]
I am getting vastly different results when using the webapp vs the cmdapp. I was expecting them to be the same, but maybe that is not the case? Do you have any advice regarding how to get similar output from the cmdapp as the webapp?

Input image:
![cat](https://user-images.githubusercontent.com/106941641/185240972-284469ca-f6bd-4273-97c2-fc27232cc22e.png)

Webapp output:
![export-2022-08-17 205335](https://user-images.githubusercontent.com/106941641/185241168-fff66a1b-b525-409f-af5e-520e0c0d7da6.svg)

Cmdapp output:
![out](https://user-images.githubusercontent.com/106941641/185241225-826a8677-0f7c-4c36-9d38-de566bb7aa29.svg)

The command I called (argument values match the webapp):
```sh
vtracer
    --filter_speckle=4
    --color_precision=6
    --gradient_step=16
    --mode=spline
    --corner_threshold=60
    --segment_length=4
    --splice_threshold=45
    --hierarchical=stacked
    --colormode=color
    --input=cat.png
    --output=out.svg
```

```sh
vtracer --version
visioncortex VTracer 0.4.0
```

**Comment by tyt2y3** [comment]
Seems like the clustering step produces nothing. Can you try one of the presets, i.e. `poster`?

**Comment by jsscheller** [comment]
I tried the `poster` preset as well as the others but it didn't change the output.

**Comment by tyt2y3** [comment]
Oh then it can be down to how `image` decodes image differently than the browser, specifically something about the alpha channel?

**Comment by jsscheller** [comment]
You are correct. Adding a background solves the issue. Thanks!
