### ISSUE TITLE
improvement for straight lines on low rez image

### ISSUE THREAD

**Issue by ash-f** [visioncortex/vtracer#27]
I would like you to improve straight line tracing on low rez image.
They tend to be wavy or ragged.
This is important for font/logo creation.
Result on Potrace is often better for now.

**Comment by tyt2y3** [comment]
The VTracer algorithm (or philosophy behind it) leans on fidelity, which means it's not going to impose assumptions on the curvature being elliptic or corners being very sharp.
In practice it's only going to make a difference at low resolution.

**Comment by ash-f** [comment]
I see.
