### ISSUE TITLE
Is there any plan to provide standalone app based on Electron

### ISSUE THREAD

**Issue by blacklein** [visioncortex/vtracer#33]
Is there any plan to provide standalone app based on Electron.

**Comment by tyt2y3** [comment]
No such plan, quite frankly. I think the web app is pretty close, and you might be (?) able to make it work offline as well.

**Comment by blacklein** [comment]
webapp build failed so i think its better to have a standalone app

**Comment by tyt2y3** [comment]
There is pre-built binaries under `/docs` if that might help

**Comment by tyt2y3** [comment]
close as duplicate to #28
