### ISSUE TITLE
VTracer not tracing image properly

### ISSUE THREAD

**Issue by Shmacked** [visioncortex/vtracer#34]
In these instances, I have an image with a white background and some black designs - its a bmp image saved as a png. Tracing on both my windows machine and my linux machine yields the same results -> a black background and some undetermined colors for the black objects from the original image. It's a rather difficult problem for me to replicate, but here are some file to demonstrate the problem with:
![196](https://user-images.githubusercontent.com/19714390/208264899-3dce8f55-8834-4221-ab31-b3bea2450b56.png)
![178](https://user-images.githubusercontent.com/19714390/208264929-2abefede-71d1-479e-bad2-af4dc078831d.png)

Trace them yourselves and see if you get a black background.

**Comment by tyt2y3** [comment]
It works for me, at least when running in b/w mode

**Comment by Shmacked** [comment]
Ah, yes. My bad. For some reason, I thought that the only command line options available to me were --input and --output.
