### ISSUE TITLE
Docker web app image file

### ISSUE THREAD

**Issue by derekmerck** [visioncortex/vtracer#35]
I wrote a Dockerfile for running the vtracer web app in a container.  It may be useful to someone else.

https://gist.github.com/derekmerck/1b8b1a3ceefd0d0184ad96cd419f106e

I'm not very familiar with rust or node, so it may not be elegant -- but it seems to work on my m1-mac.

Thanks to devs/VisionCortex for making vtracer available.  I've been trying to figure out how to automate image vectorization for a while and this looks really thoughtfully done and promising.

**Comment by tyt2y3** [comment]
Thank you. It's not an issue, but let's just leave it here open?

A Python script that acts as a HTTP server should work too, actually the only hassle is to serve the wasm file with a correct MIME type.
