### ISSUE TITLE
'cutout' clustering (as opposed to stacked)

### ISSUE THREAD

**Issue by piaoger** [visioncortex/vtracer#4]
I tried "Gum Tree" in both vtracer and a tool called VectorMagic yesterday. 
It seems VectorMagic does a better job on classification(by color?), object grouping and no overlapping between the polygons.

- classification and grouping

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/179429/101726525-aaac2280-3aed-11eb-8bd2-15a33e8b9751.png">

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/179429/101726565-bef01f80-3aed-11eb-8a64-e8c0cada42a6.png">

- Result SVG from VectorMagic

[Gum Tree Vector_vectormagic.svg.zip](https://github.com/visioncortex/vtracer/files/5670509/Gum.Tree.Vector_vectormagic.svg.zip)

**Comment by tyt2y3** [comment]
Thank you for your report. I think there are different approaches in grouping clusters. For example, Adobe provides two modes, 'stacked' and 'cutout'. Currently VTracer implements 'stacked'. And the strategy you saw in VectorMagic is 'cutout'. Both methods have there pros and cons, and 'cutout' suffers from 1. white seam between patches (as attached) and 2. generated output complexity is very high for non-vector images.

That said, we shall implement 'cutout' strategy in VTracer later

![white seam between patches](https://user-images.githubusercontent.com/1782664/101766170-5e78d680-3b1d-11eb-996c-cb83a096f83e.png)

**Comment by tyt2y3** [comment]
https://github.com/visioncortex/vtracer/commit/0b37051d40444e876ec90b3aae245eb489c18a88
Cutout mode added
