### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by wsy000-com** [visioncortex/vtracer#43]
Have you published any relevant papers? I would like to read them. If so, could you please give me a link address

**Comment by tyt2y3** [comment]
I am out of academia for too long. However, we have bits of knowledge compiled in article format on visioncortex.org

If you have anything you are interested in we can start a discussion.

**Comment by wsy000-com** [comment]
> 我离开学术界太久了。但是，我们有一些知识以文章格式汇编 visioncortex.org
> 
> 如果您有任何感兴趣的内容，我们可以开始讨论。

thank you very much
