### ISSUE TITLE
Website vs exe quality 

### ISSUE THREAD

**Issue by gitihobo** [visioncortex/vtracer#47]
I copied all parameters and got a similar but less sharp result from the exe than from https://www.visioncortex.org/vtracer/

My settings
 --input <input> --output <output> --colormode color --filter_speckle 1 --color_precision 8 --gradient_step 0 --mode pixel --corner_threshold 0 --segment_length 10 --splice_threshold 0

The online version also seems to output a larger image when putting the svg in browser which is ironic considering its svg

How can I make sure my svg is as big and sharp as the original image?

**Comment by tyt2y3** [comment]
They should not (or rather not) have any difference, because the 95% of the underlying is the same.

The parts that differ:

1) image decoder (browser vs pure Rust)
2) svg output
3) parameters to the algorithm
4) the cmdapp has an extension that can discard transparent regions

Can you inspect the source of both SVGs? I suspect that it might be a difference of the viewbox or something

**Comment by gitihobo** [comment]
I figured out what it is, on the exe it doesnt let me put --filter_speckle 0 it says it has to be 1-16 thread 

'main' panicked at 'Out of Range Error: Filter speckle is invalid at 0. It must be within [1,16].', cmdapp\src\config.rs:244:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 

While online I can

**Comment by tyt2y3** [comment]
Great! if that's the case then it'd be a simple patch, however I might not release another version too soon.

**Comment by gitihobo** [comment]
I see, well thank you for your work, is there any workaround I can do or something I can help with for the meanwhile or should I stick to the online version?

**Comment by tyt2y3** [comment]
Yes, I confirmed that the web GUI allows filter_speckle to be 0.

If you know how to build Rust, you can checkout this repo and do:

```
cargo install --git https://github.com/visioncortex/vtracer
```

**Comment by gitihobo** [comment]
I failed to install the patched master when I tried, can you tell me a step by step way on how to do it (sorry im a noob)

**Comment by yusuf-mutlu** [comment]
If your image has transparent background, it doesn't create a nice svg. Try it with an image with white background.

**Comment by gitihobo** [comment]
its a code issue I wonder if it was fixed yet

**Comment by yusuf-mutlu** [comment]
I downloaded the exe from here: https://github.com/visioncortex/vtracer/releases/tag/0.5.0 after I wrote above command and it worked fine. 

This is how I use it:

> vtracer.exe --input input.png --output output.svg --colormode color --filter_speckle 16 --color_precision 8 --gradient_step 16 --mode spline --corner_threshold 60 --segment_length 4 --splice_threshold 45

**Comment by gitihobo** [comment]
but does it look exactly like the original image? Because I can only get that to happen in the website, its very similar but not the same with the exe

**Comment by yusuf-mutlu** [comment]
I have nice edges and I am happy with the result.  It very much looks like the one in the website.

**Comment by tyt2y3** [comment]
I have an idea and a vague plan on to developing an image upscaler and denoiser, which would drastically improve the tracing quality of jpeg inputs.

**Comment by tyt2y3** [comment]
New binaries were released https://github.com/visioncortex/vtracer/releases/tag/0.6.0
