### ISSUE TITLE
How to install vtracer

### ISSUE THREAD

**Issue by Richar-Du** [visioncortex/vtracer#48]
I want to use vtracer locally, but after downloading vtracer-linux, I do not know how to install it. Both `bash vtracer-linux` and `vtracer-linux -V` fails. I also try vtracer-mac-m1 on my Mac, it fails as well. Can you help me? Thanks in advance :)

**Comment by tyt2y3** [comment]
Usually it's 

```sh
chmod +x vtracer
./vtracer
```
