### ISSUE TITLE
Python binding available at https://pypi.org/project/vtracer/

### ISSUE THREAD

**Issue by etjones** [visioncortex/vtracer#51]
Repo is https://github.com/etjones/vtracer_py

I've highlighted that you guys are the authors and linked to you from the README. Holler if you'd like to see any changes there. Cheers

**Comment by tyt2y3** [comment]
That's great! How does the binding work? I found it using maturin. If it's not a cumbersome process, I'd like to maintain an official binding for Python.

**Comment by tyt2y3** [comment]
You mentioned

> [VTracer](https://github.com/visioncortex/vtracer) doesn't expose in-memory image transforms, so we don't do that in Python

There is no technical reason for this, other than being lazy. So if you have some spare time may be we can collobrate on that.

**Comment by etjones** [comment]
The binding uses Maturin. It would probably be pretty simple to include it in this original repo rather than have separate projects; I figured I'd include it as a separate one so I wasn't asking anything of you guys. If you're interested, though, I could definitely include it as a PR so it could be maintained with the current repo. That would actually make some of the type wrapping easier. 

It looks like we could wrap the calls to `color_clusters::Runner` pretty easily and allow in-memory conversions. I'm not super confident about normal Python in-memory image formats (Numpy arrays) as opposed to what Rust uses. It's possible this could be very easy, and also possible that the memory wrangling between the two is more trouble than it's worth. 

More once I try incorporating the Python wrapper into this repo

**Comment by tyt2y3** [comment]
Cool. A PR will definitely be welcomed! Just one more question, so it's a source binding, and users would need to compile the library on their machine, am I right?

I would say representing images as [RGBA8888](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) should be universal.

**Comment by etjones** [comment]
I *think* that Maturin’s settings will take care of cross-compiling, but I haven’t tested this out yet. As currently deployed, `pip install vtracer` installs a working version of the vtracer library on MacOS Arm64 machines without needing a Rust install. I haven’t tested on X86  or Linux yet; I think there may be some more settings I need to mess with to make this happen. In any case, the (reachable!) goal is not to require any client side compilation

RGBA8888 should be universal, but there are enough other corner case options (OpenCV natively uses RBG, alpha channels are hit-or-miss, single-channel images are actually great for vector art) that I'm fine putting in-memory conversions off a little bit. I think getting valid builds for all supported platforms is probably the first step. VTracer doesn't do Windows, right? That's a relief
