### ISSUE TITLE
d attribute of path always has too long float/double value, should trunc it

### ISSUE THREAD

**Issue by origel** [visioncortex/vtracer#6]
For example,   212.15999999999997 just like 212.16 is enough，212.2 is ok too.

this is a piece of sample svg result:

<svg id="svg" version="1.1" xmlns="http://www.w3.org/2000/svg" style="display: block;" viewBox="0 0 934 624"><path d="M0 0 C308.22 0 616.44 0 934 0 C934 205.92000000000002 934 411.84000000000003 934 624 C625.78 624 317.55999999999995 624 0 624 C0 418.08 0 212.15999999999997 0 0 Z " transform="translate(0,0)" style="fill: #586E32;"/><path d="M0 0 C308.22 0 616.44 0 934 0 C934 103.62 934 207.24 934 314 C927.2490555415632 315.1251574097394 927.2490555415632 315.1251574097394 924.008544921875 315.373046875 C923.283059539795 315.42980590820315 922.5575741577148 315.48656494140624 921.8101043701172 315.5450439453125 C921.0413246154785 315.60236694335936 920.2725448608398 315.65968994140627 919.48046875 315.71875 C918.6636311340332 315.7815515136719 917.8467935180664 315.84435302734374 917.0052032470703 315.9090576171875 C915.2764339105979 316.0413969049565 913.5475643865229 316.1724331024185 9.........

**Comment by mootari** [comment]
I would prefer to see this implemented as a "precision" parameter. Depending on the use case for the generated SVG, rounding to one or even two decimal places might still not be precise enough.

**Comment by tyt2y3** [comment]
Good suggestion. Yes, rounding off would reduce file size significantly in some cases.

**Comment by tyt2y3** [comment]
Oh I mean, two people in distinct places show up at once? What a day :)

**Comment by origel** [comment]
> Oh I mean, two people at distinct places show up at once? What a day :)

haha.

**Comment by tyt2y3** [comment]
d0593e716ab527a2a59b3d60aa1cb23172fa2fe5
https://github.com/visioncortex/visioncortex/commit/065b9dc21be848a35df01fc324eb32dd9beedd50
[0.4.0](https://github.com/visioncortex/vtracer/releases/tag/0.4.0)

**Comment by tyt2y3** [comment]
@origel Close this issue if it works for you

**Comment by origel** [comment]
OK

**Comment by tyt2y3** [comment]
Great thanks!
