### ISSUE TITLE
Bug: undeclared crate or module `vtracer`

### ISSUE THREAD

**Issue by sakura6264** [visioncortex/vtracer#61]
When I use this crate version 0.6.1, I cannot use vtracer::*.
Change the version back to 0.5.0 could solve this problem.
```
error[E0433]: failed to resolve: use of undeclared crate or module `vtracer`
  --> src\app\app.rs:13:21
   |
13 |             config: vtracer::Config::default(),
   |                     ^^^^^^^ use of undeclared crate or module `vtracer`
```

**Comment by tyt2y3** [comment]
Nothing changed in 0.6 anyway. Anyway, I just publish a change making it an `rlib` as well. Let me know if it works.

**Comment by sakura6264** [comment]
It works. Many thanks.
